name = "ECCompute"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ECCompute"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "3de5ed81cc71b9ea62597b865ba0baaeb5eb0ea9"

[[lean_lib]]
name = "ECCompute"
