name = "ECCompute"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ECCompute"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "e3b73828b03c9961c9b33aa95f1d2dc0dca82028"

[[lean_lib]]
name = "ECCompute"
